(library
 (name probe_common)
 (modules probe_common)
 (libraries
  hike
  bap
  bap-core-theory
  bap-main
  bap-future
  cbat_vsa
  cbat_vsa_domain
  core_kernel
  graphlib
  threads)
 (flags
  (:standard -g -alert -deprecated))
 (preprocess
  (pps ppx_bap)))

(executable
 (name audit02)
 (modules audit02)
 (libraries
  hike
  bap
  bap-core-theory
  bap-main
  cbat_vsa
  cbat_vsa_domain
  core_kernel
  bap-future
  threads)
 (flags
  (:standard -g -alert -deprecated))
 (preprocess
  (pps ppx_bap)))

(executable
 (name stage_timer)
 (modules stage_timer)
 (libraries
  probe_common
  hike
  bap
  bap-core-theory
  bap-main
  bap-future
  cbat_vsa
  cbat_vsa_domain
  core_kernel
  graphlib
  threads)
 (flags
  (:standard -g -alert -deprecated))
 (preprocess
  (pps ppx_bap)))

(executable
 (name conv_diag)
 (modules conv_diag)
 (libraries
  probe_common
  hike
  bap
  bap-core-theory
  bap-main
  bap-future
  cbat_vsa
  cbat_vsa_domain
  core_kernel
  graphlib
  threads)
 (flags
  (:standard -g -alert -deprecated))
 (preprocess
  (pps ppx_bap)))

(executable
 (name dump_tags)
 (modules dump_tags)
 (libraries
  probe_common
  hike
  bap
  bap-core-theory
  bap-main
  bap-future
  cbat_vsa
  cbat_vsa_domain
  core_kernel
  graphlib
  threads)
 (flags
  (:standard -g -alert -deprecated))
 (preprocess
  (pps ppx_bap)))

(executable
 (name vsa_debug)
 (modules vsa_debug)
 (enabled_if (= %{profile} vsa-debug))
 (libraries
  probe_common
  hike
  bap
  bap-core-theory
  bap-main
  bap-future
  cbat_vsa
  cbat_vsa_domain
  core_kernel
  graphlib
  threads)
 (flags
  (:standard -g -alert -deprecated))
 (preprocess
  (pps ppx_bap)))

(executable
 (name wbig_diag)
 (modules wbig_diag)
 (enabled_if (= %{profile} vsa-debug))
 (libraries
  probe_common
  hike
  bap
  bap-core-theory
  bap-main
  bap-future
  cbat_vsa
  cbat_vsa_domain
  core_kernel
  graphlib
  threads)
 (flags
  (:standard -g -alert -deprecated))
 (preprocess
  (pps ppx_bap)))


(executable
 (name subtimes)
 (modules subtimes)
 (libraries
  probe_common
  hike
  bap
  bap-core-theory
  bap-main
  bap-future
  cbat_vsa
  cbat_vsa_domain
  core_kernel
  graphlib
  threads)
 (flags
  (:standard -g -alert -deprecated))
 (preprocess
  (pps ppx_bap)))

(executable
 (name stageprof)
 (modules stageprof)
 (libraries
  probe_common
  hike
  bap
  bap-core-theory
  bap-main
  bap-future
  cbat_vsa
  cbat_vsa_domain
  core_kernel
  graphlib
  threads)
 (flags
  (:standard -g -alert -deprecated))
 (preprocess
  (pps ppx_bap)))

(test
 (name clpequiv)
 (modules clpequiv)
 (libraries
  probe_common
  hike
  bap
  bap-core-theory
  bap-main
  bap-future
  cbat_vsa
  cbat_vsa_domain
  core_kernel
  graphlib
  threads)
 (flags
  (:standard -g -alert -deprecated))
 (preprocess
  (pps ppx_bap)))

(executable
 (name graphstats)
 (modules graphstats)
 (libraries
  probe_common
  hike
  bap
  bap-core-theory
  bap-main
  bap-future
  cbat_vsa
  cbat_vsa_domain
  core_kernel
  graphlib
  threads)
 (flags
  (:standard -g -alert -deprecated))
 (preprocess
  (pps ppx_bap)))

(executable
 (name memostats)
 (modules memostats)
 (enabled_if (= %{profile} vsa-debug))
 (libraries
  probe_common
  hike
  bap
  bap-core-theory
  bap-main
  bap-future
  cbat_vsa
  cbat_vsa_domain
  core_kernel
  graphlib
  threads)
 (flags
  (:standard -g -alert -deprecated))
 (preprocess
  (pps ppx_bap)))

(executable
 (name census)
 (modules census)
 (libraries
  probe_common
  hike
  bap
  bap-core-theory
  bap-main
  bap-future
  cbat_vsa
  cbat_vsa_domain
  core_kernel
  graphlib
  threads)
 (flags
  (:standard -g -alert -deprecated))
 (preprocess
  (pps ppx_bap)))
